### ISSUE TITLE
group_by parameter should not be hardcoded 

### ISSUE THREAD

**Issue by anna-savchenko** [canonical/alertmanager-k8s-operator#232] opened 2024-03-06 17:07 UTC
### Enhancement Proposal

The possibility of setting the "group_by" parameter to any value is needed. This is useful, e.g. when integrating alertmanager with external monitoring solutions.

**Comment by sed-i** [comment] 2024-03-27 14:00
Currently, the rock [comes with](https://github.com/canonical/alertmanager-rock/blob/8b896e62bb7bcc12fde397c33c637a996ba35d67/0.27.0/alertmanager.yml#L5):
```
route:
  group_by: ['alertname']
```

And charm code augments it with juju topology:
https://github.com/canonical/alertmanager-k8s-operator/blob/37622c38129be88f02d04cacdec5a27972be4ace/src/config_builder.py#L101-L103

If the user provides their own config, they could specify anything they want, but it will be augmented with juju topology.

Can you please clarify what is the desired behaviour @anna-savchenko?

**Comment by sed-i** [comment] 2024-04-16 17:16
Had a followup discussion with @anna-savchenko and asked to see a how the frontend groups alerts with this setting.
Instead of adding an option for disabling grouping by topology, perhaps we could improve the default setting.

**Comment by sed-i** [comment] 2024-06-04 12:55
Related to #205.

**Comment by sed-i** [comment] 2024-06-20 21:42
Confirmed with @anna-savchenko that this is a duplicate of #205. Closing.
Feel free to reopen if you have a different spec for this.

**Closed by sed-i** 2024-06-20 21:42 UTC
Labels: Type: Enhancement, Status: Triage
